# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

block_cipher = None

# tkinterdnd2のデータファイルを収集
datas = collect_data_files('tkinterdnd2')

# プレースホルダー画像とアイコンを追加
datas += [('hippo_019.png', '.')]
datas += [('hippo_019_cir.ico', '.')]

a = Analysis(
    ['pdf_viewer.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[
        'PIL._tkinter_finder',
        'fitz',
        'pymupdf',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'tkinterdnd2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'pytest',
        'setuptools',
        'distutils',
        'unittest',
        'test',
        'email',
        'http',
        'urllib3',
        'xml.etree',
        'xml.dom',
        'xml.sax',
        'pydoc',
        'doctest',
        'asyncio',
        'concurrent',
        'multiprocessing',
        'sqlite3',
        'bz2',
        'lzma',
        'ssl',
        'socket',
        'socketserver',
        'select',
        'ftplib',
        'telnetlib',
        'smtplib',
        'poplib',
        'imaplib',
        'cgi',
        'cgitb',
        'wsgiref',
        'urllib',
        'xmlrpc',
        'pdb',
        'profile',
        'cProfile',
        'pstats',
        'difflib',
        'argparse',
        'optparse',
        'getopt',
        'wave',
        'chunk',
        'sunau',
        'aifc',
        'colorsys',
        'imghdr',
        'sndhdr',
        'ossaudiodev',
        'audioop',
        'cmath',
        'decimal',
        'fractions',
        'statistics',
        'secrets',
        'calendar',
        'pickle',
        'shelve',
        'dbm',
        'csv',
        'gzip',
        'zipimport',
        'pkgutil',
        'modulefinder',
        'runpy',
        'sysconfig',
        'tabnanny',
        'timeit',
        'trace',
        'tracemalloc',
        'turtle',
        'turtledemo',
        'venv',
        'zipapp',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PDFXyViewer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,  # Windowsではstripは使えないため無効化
    upx=True,  # UPXで圧縮
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='hippo_019_cir.ico',
)
